cross – fortran-astrodynamics-toolkit
cross Function
Jacob Williams
7 statements
Source File
public pure function cross(r, v) result(rxv)
Cross product of two 3x1 vectors
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(3) :: r
real(kind=wp), intent(in), dimension(3) :: v
Return Value real(kind=wp), dimension(3)
Called by
Contents
Source Code
cross
Source Code
    pure function cross(r,v) result(rxv)
    implicit none
    real(wp),dimension(3),intent(in) :: r
    real(wp),dimension(3),intent(in) :: v
    real(wp),dimension(3)            :: rxv
    rxv = [r(2)*v(3) - v(2)*r(3), &
           r(3)*v(1) - v(3)*r(1), &
           r(1)*v(2) - v(1)*r(2) ]
    end function cross
Call graph
get_c_cdot_two_body_rotating calls cross
ucross calls cross
distance_from_point_to_line calls cross
calculate_bplane_data calls cross
box_product calls cross
solve_lambert_gooding calls cross
rv_to_orbital_elements calls cross
compute_vinf_vectors calls cross
axis_angle_rotation calls cross
bplane calls cross, ucross
cartesian_to_equinoctial calls cross
from_ijk_to_lvlh_mat calls cross
from_ijk_to_rsw_mat calls cross
angle_between_vectors calls cross
from_ijk_to_lvlh calls from_ijk_to_lvlh_mat, from_ijk_to_lvlh_rv
solve_lambert_izzo calls ucross
lambert_test calls solve_lambert_gooding, solve_lambert_izzo
vector_test calls axis_angle_rotation
sphere_of_influence_earth_moon calls angle_between_vectors
from_ijk_to_rsw calls from_ijk_to_rsw_mat, from_ijk_to_rsw_rv
bplane_test calls calculate_bplane_data, compute_vinf_vectors, bplane
modified_equinoctial_test calls cartesian_to_equinoctial
from_ijk_to_lvlh_rv calls from_ijk_to_lvlh
from_ijk_to_rsw_rv calls from_ijk_to_rsw
from_lvlh_to_ijk_mat calls from_ijk_to_lvlh
relative_motion_test calls from_ijk_to_lvlh, from_ijk_to_rsw
from_rsw_to_ijk_mat calls from_ijk_to_rsw
from_rsw_to_ijk calls from_rsw_to_ijk_mat, from_rsw_to_ijk_rv
from_lvlh_to_ijk calls from_lvlh_to_ijk_mat, from_lvlh_to_ijk_rv
from_rsw_to_ijk_rv calls from_rsw_to_ijk
from_lvlh_to_ijk_rv calls from_lvlh_to_ijk